[tool.poetry]
name = "template-python"
version = "0.0.0"
description = "Service to define"
authors = [ "kpler <engineering@kpler.com>" ]
license = "Copyright"
packages = [
    { include = "kpler", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.9.16"
pydantic = "1.10.18"
json_log_formatter = "1.1.1"
uvicorn = "0.34.3"
fastapi = "^0.115.12"
poetry-dynamic-versioning = { extras = ["plugin"], version = "~1.8.2" }

[tool.poetry.group.cli]
optional = true
[tool.poetry.group.cli.dependencies]
click = "8.2.1"

[tool.poetry-dynamic-versioning]
enable = true

[tool.poetry.scripts]
calibration = "kpler.oam_tanks_from_sar.cli.calibration:calibration"

[build-system]
requires = ["poetry-core>=2.1.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"